### ISSUE TITLE
Sistema não deixa logar, nem trocar senha (emails não chegam)

### ISSUE THREAD

**Issue by lskbr** [apyb/associados#220]
O que fiz:
- Tentei logar com minha senha: dá um erro (senha incorreta, mas a mensagem não é clara).
- Tentei redefinir a senha, mas ou da Ops ou não envia o email.

**Comment by mazulo** [comment]
@lskbr configurei o sentry no projeto e tentei fazer um reset de senha. Agora temos um pouco mais de informações sobre o que tá acontecendo:

![image](https://user-images.githubusercontent.com/1661112/138382480-1eed2fef-0609-44ea-8cbb-001470a3124e.png)

Issue no sentry: https://sentry.io/organizations/associados-4c/issues/2736455095/?project=1799053&query=is%3Aunresolved

**Comment by mazulo** [comment]
Descobri o problema. O que tá acontecendo é que a conta do SendGrid usada no sistema foi desativada 😬 amanhã vou tentar criar outra, ou até substituir pelo MailGun, caso seja mais fácil.

**Comment by rougeth** [comment]
@lskbr você ainda está tendo o mesmo problema? Acredito que os envios de e-mail estão funcionando agora.

**Comment by rougeth** [comment]
Fechando a issue, podemos reabri-la caso volte acontecer.
