### ISSUE TITLE
Facilitar o pagamento para não residentes no Brasil

### ISSUE THREAD

**Issue by rodolphoeck** [apyb/associados#96]
Não resido mais no Brasil, mas quero renovar minha associação. Atualmente, o pagamento é redirecionado ao PagSeguro, que exige telefone e endereço (CEP) no Brasil. Seria legal se pudesse colocar meus dados reais no campos e continuar com o pagamento.
Obrigado e parabéns pelo novo sistema!

**Comment by ocarneiro** [comment]
Eu acho que enquanto forem poucos casos (até 5, eu diria), dá pra tratar caso a caso sem implementar no sistema. Bastaria ter uma indicação "quer pagar de outra forma? Mande e-mail para ...". Se aparecerem muitos, retoma-se a discussão.

**Comment by filipecifali** [comment]
Recuperando a thread, quando o próprio modelo atual é difícil de gerenciar pelo próprio django para dizer se o associado está válid ou não eu acho que essa issue ainda precisa ser modificada, o @romulocollopy já deu uma boa modificada no acoplamento: https://github.com/pythonbrasil/associados/pull/154 ai podemos lançar outras plataformas de pagamento no sistema.

**Comment by lskbr** [comment]
Acordando esta issue novamente, mas hoje é muito fácil integrar com Stripe, Braintree, etc. Se ainda houver interesse, vamos conversar.

**Comment by rougeth** [comment]
+11 anos depois, acho que podemos finalmente fechar essa issue :D https://github.com/apyb/comunidade/discussions/139.

Só faltava a incrível @naanadr chegar na APyB 🤣. @rodolphoeck @lskbr animam testar o novo fluxo?

**Comment by naanadr** [comment]
Vou aguardar o @rodolphoeck e o @lskbr testar o fluxo novo para fechar a issue 😃

**Comment by rodolphoeck** [comment]
Obrigado!! Testei aqui e funcionou.

Só um feedback: depois de completar o pagamento, fui redirecionado para a página apyb.python.org.br mas sem menssagem de sucesso ou aviso de erro. Verifiquei meu inbox e também nada. Acabei verificando manualmente pelo Stripe que estava tudo ok. Alguns minutos depois recebi um email com a fatura e recibo. Acho que seria melhor se logo no final de completar a assinatura tivesse uma mensagem de sucesso e boas vindas.

Obrigado @naanadr !

**Comment by naanadr** [comment]
Obrigada pelo feedback @rodolphoeck . Habilitei a página de confirmação, ela vai ser algo desse tipo:

![image](https://github.com/user-attachments/assets/6083c537-9db6-4917-896f-6c21099f2d91)
